language: node_js
node_js:
  - stable
install:
  - npm install
script:
  - npx commitlint -e
  - npm run lint
  - npm run dtslint
  - npm run cover
  - npm run build
  - npm run benchmark
after_script:
  - npm run coveralls
cache:
  directories:
    - node_modules
notifications:
  email: false
