language: node_js
node_js:
  - stable
install:
  - npm install
script:
  # Lint last commit message from history
  - npx commitlint --from=HEAD~1
  - npm run lint
  - npm run lint:dts
  - npm run test:ci
  - npm run build
  - npm run benchmark
after_success:
  - cat coverage/lcov.info | npx coveralls
cache:
  directories:
    - node_modules
notifications:
  email: false
